# Generated by Django 3.2.9 on 2021-11-03 14:43

from django.db import migrations, models
import django.db.models.deletion
import donor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('blood_type', models.CharField(choices=[('101', 'A+'), ('100', 'A-'), ('201', 'B+'), ('200', 'B-'), ('121', 'AB+'), ('120', 'AB-'), ('301', 'O+'), ('300', 'O-')], max_length=3)),
                ('blood_virus_test', models.BooleanField(null=True)),
                ('last_donor_date', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.city')),
            ],
        ),
    ]
