# Generated by Django 3.2.9 on 2021-11-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('name', 'national_id')},
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
        migrations.AddField(
            model_name='donor',
            name='can_donate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_virus_test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
