# Generated by Django 3.2.9 on 2021-11-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20211103_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='blood_type',
        ),
    ]
