# Generated by Django 3.2.9 on 2021-11-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donor_blood_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtype',
            options={'ordering': ('name',)},
        ),
    ]
