# Generated by Django 3.2.9 on 2021-11-03 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_options'),
        ('donor', '0006_alter_bloodtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='can_donate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('satus', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=8)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(default=datetime.datetime(2021, 12, 15, 23, 59, 58, 696650, tzinfo=utc))),
                ('blood_bank_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.city')),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.bloodtype')),
            ],
        ),
    ]
