# Generated by Django 3.2.9 on 2021-11-04 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20211103_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 0, 2, 0, 556568, tzinfo=utc)),
        ),
    ]
