# Generated by Django 3.2.9 on 2021-11-04 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_auto_20211104_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='blood_virus_test',
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 15, 13, 52, 391632, tzinfo=utc)),
        ),
    ]
