# Generated by Django 3.2.9 on 2021-11-04 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_auto_20211104_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_virus_test',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Positive', 'Positive'), ('Negative', 'Negative')], default='Unknown', max_length=8),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 15, 15, 21, 347664, tzinfo=utc)),
        ),
    ]
