# Generated by Django 3.2.9 on 2021-11-04 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_auto_20211104_1515'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 17, 14, 41, 827328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
