# Generated by Django 3.2.9 on 2021-11-04 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_auto_20211104_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('donor',)},
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='satus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 17, 18, 39, 927613, tzinfo=utc)),
        ),
    ]
