# Generated by Django 3.2.9 on 2021-11-04 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_options'),
        ('donor', '0014_auto_20211104_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=400, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_bank_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 21, 34, 35, 807156, tzinfo=utc)),
        ),
    ]
