# Generated by Django 3.2.9 on 2021-11-06 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_auto_20211106_2030'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 18, 21, 6, 12, 687310, tzinfo=utc)),
        ),
    ]
