# Generated by Django 3.2.9 on 2021-11-07 14:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_auto_20211106_2106'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 14, 47, 24, 436808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
