# Generated by Django 3.2.9 on 2021-11-08 01:01

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0019_auto_20211107_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodstock',
            options={'ordering': ('-expiration_date',)},
        ),
        
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 20, 1, 1, 42, 275723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
