# Generated by Django 3.2.9 on 2021-11-11 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_auto_20211108_0101'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 23, 17, 6, 5, 275359, tzinfo=utc)),
        ),
    ]
