# Generated by Django 3.2.9 on 2021-11-13 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0022_auto_20211112_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 25, 16, 55, 13, 991477, tzinfo=utc)),
        ),
    ]
