# Generated by Django 3.2.9 on 2021-11-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name_plural': 'Cities'},
        ),
    ]
