# Generated by Django 3.2.9 on 2021-11-07 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_options'),
        ('recepient', '0002_auto_20211106_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.CreateModel(
            name='BloodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blood_bank_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BloodBank', to='city.city')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='AcceptedRequest', to='recepient.request')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
