# Generated by Django 3.2.9 on 2021-11-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepient', '0003_auto_20211107_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodTransaction',
        ),
    ]
