# Generated by Django 3.2.9 on 2021-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepient', '0004_delete_bloodtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='patient_status',
            field=models.CharField(choices=[(1, 'Immediate'), (2, 'Urgent'), (3, 'Normal')], max_length=9),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
