# Generated by Django 3.2.9 on 2021-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepient', '0005_auto_20211113_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='patient_status',
            field=models.IntegerField(choices=[(1, 'Immediate'), (2, 'Urgent'), (3, 'Normal')], max_length=9),
        ),
    ]
