# Generated by Django 3.2.9 on 2021-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepient', '0006_alter_request_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='patient_status',
            field=models.IntegerField(choices=[(1, 'Immediate'), (2, 'Urgent'), (3, 'Normal')]),
        ),
    ]
