# Generated by Django 3.2.9 on 2021-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopitaluser',
            name='hospital_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
