# Generated by Django 3.2.9 on 2021-11-06 19:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0003_alter_city_options'),
        ('authentication', '0002_hopitaluser_hospital_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HopitalUser',
            new_name='HospitalUser',
        ),
    ]
