# Generated by Django 3.2.9 on 2021-11-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_hopitaluser_hospitaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaluser',
            options={'ordering': ('hospital_name',)},
        ),
    ]
