# Generated by Django 3.2.9 on 2021-11-11 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0021_auto_20211111_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0003_alter_city_options'),
        ('authentication', '0004_alter_hospitaluser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('blood_virus_test', models.CharField(choices=[('Unknown', 'Unknown'), ('Positive', 'Positive'), ('Negative', 'Negative')], default='Unknown', max_length=8)),
                ('can_donate', models.BooleanField(default=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.bloodtype')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'national_id'),
            },
        ),
    ]
