# Generated by Django 3.2.9 on 2021-11-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_donoruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoruser',
            name='can_donate',
            field=models.BooleanField(default=False),
        ),
    ]
